### ISSUE TITLE
  executeQuery() and prepareGlobalResultSet()

### ISSUE THREAD

**Issue by joe42** [mockrunner/mockrunner#11]
Hi,

First of all, thanks for creating mockrunner. I have used it for a few days and already I like it a lot.
Issue #8 was closed, ignoring the issue @frab3 raised. I experience the same misbehaviour, so here is the new issue.
I get an empty result set, but expect a result set with ID and USERNAME. Here is a working example with a workaround:

	import java.sql.*;
	import java.util.HashMap;
	import org.junit.Test;
	import com.mockrunner.jdbc.BasicJDBCTestCaseAdapter;
	import com.mockrunner.jdbc.PreparedStatementResultSetHandler;
	import com.mockrunner.mock.jdbc.MockResultSet;
	public class ExtractDataTest extends BasicJDBCTestCaseAdapter {
		@Test
		public void test() throws Exception {
			PreparedStatementResultSetHandler statementHandler = getJDBCMockObjectFactory()
					.getMockConnection().getPreparedStatementResultSetHandler();
			MockResultSet resultMock = statementHandler.createResultSet();
			resultMock.addColumn("ID", new Object[]{"1"});
			resultMock.addColumn("USERNAME", new Object[]{"foobar"});
			statementHandler.prepareGlobalResultSet(resultMock);
			// statementHandler.prepareResultSet("SELECT * FROM DUAL", resultMock, new HashMap()); // WORKAROUND
			Connection con = DriverManager.getConnection( "a", "b", "c");
			System.out.println(con); //com.mockrunner.mock.jdbc.MockConnection@29d8a2c5
			PreparedStatement stmtObjects = con.prepareStatement(
					  "SELECT * FROM DUAL WHERE 1=?"); //SELECT * FROM DUAL would work, too.
			ResultSet rs = stmtObjects.executeQuery();
			System.out.println(rs);
			System.out.println(this.getPreparedStatements());
		}
	}

I first raised the issue on stackoverflow, so it would be great if you could write a comment there if you fix the bug.
http://stackoverflow.com/questions/28676123/mockrunner-jdbc-no-columns-rows-in-result-set/28691264#28691264

**Comment by cemartins** [comment]
Hi Joe,

Thanks for writing and for your workaround. I will try and fix that bug
when I get some time to dedicate to mockrunner again.

I am not the creator of mockrunner. Alwin Ibba and some friends created it.
I only mavenized it and brought it over to Github and I did so because I
was using a specific module for JMS testing and I needed a mockrunner-jms
from the 21st century.

I understand mockrunner was already being used for a long time and I
thought the code there would be quite stable, but apparently not.

I find it hard to patch code that was written many years ago by someone
else whose coding practices I am not familiar with, so any help would be
very welcome. I would be very glad to give you commit rights to mockrunner
if you feel inclined to be part of the maintainers.

Kind regards
Carlos

**Comment by joe42** [comment]
Hi Carlos,

Thanks anyway for maintaining the project.
The workaround can not be applied when you want to add several MockResultSets; prepareResultSets seems to suffer from the same bug. So I am probably going to try to write a bugfix, since I already browsed the code anyway.

**Comment by InfoSec812** [comment]
Pull requests are always appreciated!

**Comment by joe42** [comment]
Hi,

Thanks to your support, I was able to set up the complete mockrunner project in eclipse and import it into my project. With this, the above code works as expected. But if I import the required dependencies as jar archives instead, the result set is empty. Here are the jars that I downloaded:

    $ md5sum mockrunner*
    cf13c6335bae42c7cc8d77b8eedafc10  mockrunner-core-1.0.5.jar
    397643986242e2d53a72328f040b66d0  mockrunner-jdbc-1.0.5.jar

So the only explanation coming to mind is that there has already been a bugfix in master. Is there an up-to-date jar archive?

Thanks,
Joe

**Comment by InfoSec812** [comment]
There are very likely changes in 'master' which have not been published to
maven central yet. Carlos could probably help with that.

Deven Phillips
from my mobile

**Comment by cemartins** [comment]
Sure. I will do new a release. Will let you know when it's published.

**Comment by cemartins** [comment]
Hi Deven. 

I don't see any commits after November 22nd when 1.0.5 was released. Am I missing something?

**Comment by joe42** [comment]
The jar file is labeled 1.0.5, so I think thats the version I use. I posted the MD5 sums of the files above. Could you try to reproduce the output of the program with the jars from http://mvnrepository.com/artifact/com.mockrunner v.1.0.5 vs. the master branch?

**Comment by cemartins** [comment]
I performed a new release (just in case) mockrunner-1.0.6 is out. Can you try that?

**Comment by joe42** [comment]
I just did, but it does not solve the issue.

**Comment by cemartins** [comment]
Just a note about the issue #8 and @frab3: I did not ignore it. In fact I reverted the initial change I had done to AbstractParameterResultSetHandler since he said that change introduced a bug.

I created a Test Case with the code you submitted and did some debugging. It turns out that `stmtObjects.executeQuery();` returns a new resultSet despite the initial setup of resultMock and the execution of `statementHandler.prepareGlobalResultSet(resultMock);`

Nevertheless, this behaviour seems to be what the initial developers intended and not the result of the changes from the migration to Guthub.

I think it is best not to "fix" the intricate code that lies underneath these classes because it would very likely introduce new bugs.
A better approach would be to refactor the whole thing while bringing it inline with Java 8 and the latest JDBC specs, for mockrunner-2.0.0 perhaps - Huge task - Contributions needed!

**Comment by kz282** [comment]
This issue is caused by `MockPreparedStatement.executeQuery(...)` is not using `AbstractResultSetHandler.getGlobalResultSets()` for providing a ResultSet to previously non-prepared PreparedStatements. 

This might not be a big issue after all, as statements are to be predefined anyway. The bigger issue is be that it is quite deceiving, as the ...ResultSetHandlers are inherited...
